---
- name: Install package
  become: True
  package:
    name: hyperkube
    state: present

- name: Configure package
  become: True
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    owner: root
    group: root
    mode: 0640
  notify:
    - Reload systemd
    - Restart kube-scheduler
