---
- name: Install package
  become: True
  package:
    name: kubernetes-hyperkube-kube-scheduler
    state: present
    update_cache: True

- name: Configure package
  become: True
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: systemd.service.j2
      dest: /etc/systemd/system/kube-scheduler.service
    - src: config.conf.j2
      dest: /etc/kubernetes/kube-scheduler/config.conf
  notify:
    - Reload systemd
    - Restart kube-scheduler
